services:
  kibana:
      image: kibana:7.17.27
      container_name: kibana1
      restart: always
      ports:
        - "5601:5601"
      environment:
        # es访问地址
        ELASTICSEARCH_HOSTS: '["http://192.168.2.101:9200"]'
        # kibana语言配置：en、zh-CN、ja-JP
        I18N_LOCALE: "zh-CN"